/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

import com.example.gradleproject1.example.Student;

public class App {
    public String getGreeting() {
        return "bhole babba dede nott chapann de machine eee";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
//        Fun1 f = new Fun1();
//        System.out.println(f.x);

        Student s = new Student(120,"ram");
         System.out.println(s.getName());
        //  System.out.println(s.name);
        
        
    }
}
